"""add_remaining_tables

Revision ID: 9f28257d9661
Revises: 733ea45c5a03
Create Date: 2025-10-01 10:10:05.181872

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f28257d9661'
down_revision: str | Sequence[str] | None = '733ea45c5a03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('couple_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('couple_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accommodations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('hotel_name', sa.String(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('transport_required', sa.Boolean(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_service_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['vendor_service_id'], ['vendor_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsvps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('plus_ones', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seating_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_status_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seating_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seating_table_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['seating_table_id'], ['seating_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seating_assignments')
    op.drop_table('vendor_status_updates')
    op.drop_table('seating_tables')
    op.drop_table('rsvps')
    op.drop_table('service_media')
    op.drop_table('accommodations')
    op.drop_table('guests')
    op.drop_table('family_members')
    # ### end Alembic commands ###
